### ISSUE TITLE
scope snap file extension

### ISSUE THREAD

**Issue by idibona27** [bveina/Rigol-Scope-Snap#1]
is there any way to incorporate a "save as" feature for the user to choose the file extension of the screen capture being saved? using latex and other word editors, the images are easier to incorporate as .jpg and .png files.

**Comment by bveina** [comment]
there  has always been a save option in the file menu, but it was limited to bmp output. png seems like a more useful option since LaTeX will work better with pngs.

This has been address as of  commits d4189b171039b67648c6e6ebda36c0b532ff0843 to  bead8be2b5832779b43ba04cdc91c3999b0703d9 by adding bmp/png as options in the save dialog option box. scope snap will default to png going forward since this is the preferred format for latex, and reports are the primary purpose of the software, and will be packaged as part of the next release. only formats that can be losslessly converted from scope data will be considered in the future so i see no benefit to jpg files.

thank you for submitting this feature request.
